# Generated by Django 3.1.5 on 2021-01-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shougonai', '0003_auto_20210108_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='post',
        ),
    ]
