# Generated by Django 3.1.5 on 2021-01-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shougonai', '0006_auto_20210120_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='new_field',
        ),
    ]
