# Generated by Django 3.1.5 on 2021-02-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shougonai', '0013_auto_20210129_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_background',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
