# Generated by Django 3.1.6 on 2021-02-22 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210222_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='github',
        ),
    ]
